version: 3

dotenv: ['.env']

tasks:
  default:
    - task --list-all

  deps:
    - scoop install llvm cmake vcpkg
    - task: install-opencv

  install-opencv:
    cmds:
    - vcpkg install opencv4[contrib,nonfree]:x64-windows-static
    - vcpkg integrate install

  build:
    cmds:
      - cargo build --workspace

  check:
    cmds:
      - cargo check --workspace --all-targets

  fmt:
    cmds:
      - cargo fmt --all

  test:
    cmds:
      - cargo test --workspace --all-targets

  frontend:
    desc: Run the Slint frontend application
    cmds:
      - |
        pwsh -NoLogo -NoProfile -Command "cargo run -p camden-frontend"

  release:
    cmds:
      - cargo build --workspace --release