version: 3

env:
  VCPKG_ROOT: "{{ .ROOT_DIR }}/.vendor/vcpkg"
  #OPENCV_LINK_PATHS: "{{ .VCPKG_ROOT }}/installed/x64-windows-static/lib"
  #OPENCV_INCLUDE_PATHS: "{{ .VCPKG_ROOT }}/installed/x64-windows-static/include/opencv4"
  RUSTFLAGS: "-C target-feature=+crt-static"

includes:
  opencv: 
    taskfile: taskfiles/opencv.yaml
    flatten: true
  build: 
    taskfile: taskfiles/build.yaml
    flatten: true
  deps: 
    taskfile: taskfiles/deps.yaml
    flatten: true
  version: 
    taskfile: taskfiles/version.yaml
    flatten: true

tasks:
  default:
    - task --list-all
