version: 3
tasks:
  default:
    - task --list-all

  deps:
    - task: install-opencv
    - scoop install llvm cmake vcpkg

  install-opencv:
    env:
      VCPKG_ROOT: "$HOME/scoop/apps/vcpkg/current"
      VCPKGS_TARGET_TRIPLET: x64-windows-static-release
      VCPKGS_HOST_TRIPLET: x64-windows-static-release
      OPENCV_STATIC: 1
    cmds:
    #- vcpkg install opencv4[contrib,nonfree] --triplet x64-windows-static-release
    - vcpkg install opencv4[contrib,nonfree]:x64-windows-static
    - vcpkg integrate install

  build:
    env:
      OPENCV_LINK_PATHS: "D:/vcpkg/installed/x64-windows-static-md/lib/"
      OPENCV_DIR: "D:/vcpkg/installed/x64-windows-static-md"
      VCPKGRS_TRIPLET: "x64-windows-static-md"
      VCPKGRS_DYNAMIC: "0"
      VCPKG_ROOT: "D:/vcpkg"
    cmds:
      - |
        d:/vcpkg/vcpkg.exe install opencv4:x64-windows-static-md
      - |
        echo OPENCV_LINK_PATHS: $OPENCV_LINK_PATHS
        echo OPENCV_DIR: $OPENCV_DIR
        cargo build

  check:
    env:
      OPENCV_LINK_PATHS: "D:/vcpkg/installed/x64-windows-static-md/lib/"
      OPENCV_DIR: "D:/vcpkg/installed/x64-windows-static-md"
      VCPKGRS_TRIPLET: "x64-windows-static-md"
      VCPKGRS_DYNAMIC: "0"
      VCPKG_ROOT: "D:/vcpkg"
    cmds:
      - |
        cargo check