version: 3

#dotenv: ['.env']

tasks:
  default:
    - task --list-all

  deps:
    - scoop install llvm #cmake vcpkg
    - task: install-opencv

  install-opencv:
    vars:
      OPENCV_VERSION: 4.12.0
    cmds:
      - |
        if [ -d ".vendor/opencv" ]; then
          echo "OpenCV is already installed in local vendor directory."
        else
          echo "Downloading OpenCV {{.OPENCV_VERSION}}..."
          curl --ssl-no-revoke -L -o opencv.exe "https://github.com/opencv/opencv/releases/download/{{.OPENCV_VERSION}}/opencv-{{.OPENCV_VERSION}}-windows.exe"
          
          echo "Extracting OpenCV..."
          mkdir -p .vendor
          # The exe is a 7zip self-extracting archive. -y assumes yes, -o specifies output dir.
          ./opencv.exe -y -o.vendor
          
          rm opencv.exe
          echo "OpenCV setup complete."
        fi

  install-vcpkg:
    cmds:
      - |
        if [ -d ".vendor/vcpkg" ]; then
          echo "vcpkg is already installed."
        else
          echo "Cloning vcpkg..."
          mkdir -p .vendor
          git clone https://github.com/microsoft/vcpkg .vendor/vcpkg
          echo "Bootstrapping vcpkg..."
          cd .vendor/vcpkg && ./bootstrap-vcpkg.bat
        fi

  install-opencv-static:
    deps: [install-vcpkg]
    cmds:
      - |
        echo "Installing static OpenCV..."
        cd .vendor/vcpkg && ./vcpkg install opencv:x64-windows-static

  check:
    silent: true
    cmds:
      - |
        export VCPKG_ROOT="$PWD\\.vendor\\vcpkg"
        # Unset dynamic linking vars to avoid conflicts
        unset OPENCV_LINK_PATHS
        unset OPENCV_LINK_LIBS
        unset OPENCV_INCLUDE_PATHS
        
        # Ensure static CRT is used if vcpkg's triplet expects it (x64-windows-static usually does)
        # We can pass rustflags via environment variable
        export RUSTFLAGS="-C target-feature=+crt-static"

        cargo check --workspace --all-targets

  fmt:
    cmds:
      - cargo fmt --all

  test:
    silent: true
    cmds:
      - |
        export VCPKG_ROOT="$PWD\\.vendor\\vcpkg"
        unset OPENCV_LINK_PATHS
        unset OPENCV_LINK_LIBS
        unset OPENCV_INCLUDE_PATHS
        export RUSTFLAGS="-C target-feature=+crt-static"
        
        cargo test --workspace --all-targets

  frontend:
    desc: Run the Slint frontend application
    cmds:
      - |
        export VCPKG_ROOT="$PWD\\.vendor\\vcpkg"
        # Unset dynamic linking vars to avoid conflicts
        unset OPENCV_LINK_PATHS
        unset OPENCV_LINK_LIBS
        unset OPENCV_INCLUDE_PATHS
        
        # Ensure static CRT is used if vcpkg's triplet expects it (x64-windows-static usually does)
        # We can pass rustflags via environment variable
        export RUSTFLAGS="-C target-feature=+crt-static"

        cargo run -p camden-frontend

  build:
    desc: Build with static OpenCV (using local vcpkg)
    silent: true
    cmds:
      - |
        export VCPKG_ROOT="$PWD\\.vendor\\vcpkg"
        # Unset dynamic linking vars to avoid conflicts
        unset OPENCV_LINK_PATHS
        unset OPENCV_LINK_LIBS
        unset OPENCV_INCLUDE_PATHS
        
        # Ensure static CRT is used if vcpkg's triplet expects it (x64-windows-static usually does)
        # We can pass rustflags via environment variable
        export RUSTFLAGS="-C target-feature=+crt-static"
        
        cargo build --workspace

  release:
    desc: Release build with static OpenCV (using local vcpkg)
    silent: true
    cmds:
      - |
        export VCPKG_ROOT="$PWD\\.vendor\\vcpkg"
        # Unset dynamic linking vars to avoid conflicts
        unset OPENCV_LINK_PATHS
        unset OPENCV_LINK_LIBS
        unset OPENCV_INCLUDE_PATHS
        
        # Ensure static CRT is used if vcpkg's triplet expects it (x64-windows-static usually does)
        # We can pass rustflags via environment variable
        export RUSTFLAGS="-C target-feature=+crt-static"
        
        cargo build --workspace --release
